language: python
python:
  - "3.6"
install:
  - pip install -U -r requirements.txt
  - pip install coveralls
script:
  pwd && ls && cd supervised && coverage run --include='./supervised' -m tests.run_all -v
after_success:
  coveralls
