language: python
python:
  - "3.6"
install:
  - pip install -U -r requirements.txt
  - pip install coveralls
script:
  cd supervised && coverage run --include='./' -m tests.run_all -v
after_success:
  coveralls
